### ISSUE TITLE
sysinfo warning on NF_(CONNTRACK|NAT)_IPV[4,6]

### ISSUE THREAD

**Issue by twmobius** [akosiaris/k0s_hetzner#1]
Ok so according to https://github.com/k0sproject/k0s/issues/2755#issuecomment-1479397695 sysinfo is somewhat of a reference on what is expected to be working where a hard fail is actually an error while warnings could be ignored, if all works as expected. I went through the code and from what I've found, sysinfo looks into the kernel config to match specific configuration parameters. 

The warnings seen in the sysinfo are for the NF_CONNTRACK_IPV4, NF_CONNTRACK_IPV6, NF_NAT_IPV4, NF_NAT_IPV6.

Specifically it seems to be loading kernel configuration from wherever it finds it as stated here: https://github.com/k0sproject/k0s/blob/647b1a86a10076cf4ff5e32dad7c129b61ac3b20/internal/pkg/sysinfo/probes/linux/kernel.go#L281 and in /boot/config-5.10.0-23-arm64 those config flags are indeed missing. 

kernelconfig.io on 5.10.184, 5.4.x in both arm/x86 has no reference for the keys in question: https://www.kernelconfig.io/config_nf_conntrack_ipv4?q=&kernelversion=5.10.184&arch=arm

That's not the case however with the 6.x branch.

Installing conntrack and running `conntrack -L` looks as if connection tracking is indeed working.

Related issues:

https://github.com/kubernetes/kubernetes/issues/97052
https://github.com/kubernetes-sigs/kubespray/pull/6988

**Comment by akosiaris** [comment]
I did a bit more digging. The conntrack stuff (both v4 and v6) is from https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a0ae2562c6c4b2721d9fddba63b7286c13517d9f (merged in 4.19) and indeed is no longer a thing that we have to even remotely care about.

That NAT thing is at https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3bf195ae6037e310d693ff3313401cfaf1261b71 (merged in 5.1) and the same as above applies
